version: "2.3"

services:
    flask_fibo:
        container_name: flask_fibo
        image: flask_fibo
        restart: always
        build:
            context: .
    
    memcached: 
        container_name: memcached
        image: memcached
        restart: always
        ports: 
            - "11211:11211"

    nginx:
        container_name: flask_fibo_proxy
        image: nginx:stable-alpine
        restart: always
        depends_on:
            - flask_fibo
        environment:
            CVAT_HOST: localhost
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf