version: "2.3"

services:
    flask_fibo:
        container_name: flask_fibo
        image: flask_fibo
        restart: always
        environment:
            PORT: 5000
            HOST: 127.0.0.1
            DEBUG: "False"
        build:
            context: .
        networks:
            my-network:
                aliases:
                    - flask-app

    memcached: 
        container_name: memcached
        image: memcached
        restart: always
        ports: 
            - "11211:11211"
        networks: 
            - my-network

    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        restart: always
        depends_on:
            - flask_fibo
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks: 
            - my-network
    
networks: 
    my-network: